1.7.0 Correções de bugs e adição de lógica para lidar com respostas da API quando o código de retorno é "GF"
LinkNacional/wc_cielo_payment_gateway pull request #41
Opened 2024-03-25 20:35 UTC by helonfranca02

* Correção de bug de carregamento de script do 3DS na opção cartão de débito;
* Adição de lógica para lidar com respostas da API quando o código de retorno é "GF";
* Ajuste na label de código de segurança;
* Adição de descrição nas configurações do cartão de débito;
* Adição de validação no campo de descrição da fatura;

2024-04-20 18:40 UTC, emanuellopess commented on includes/class-lkn-wc-gateway-cielo-credit.php
> +                'description' => __('Cielo API- sddasd 3.0 environment.', 'lkn-wc-gateway-cielo'),
@helonfranca02 Necessário retirar esse "sddasd"

2024-04-20 18:41 UTC, emanuellopess commented on includes/class-lkn-wc-gateway-cielo-credit.php
> +            $error_message = "Return Code: " . $responseDecoded->Payment->ReturnCode . '. Return Message: ' . $responseDecoded->Payment->ReturnMessage . '.' . __('Please contact Cielo for further ass
@helonfranca02 No caso de mensagens a serem traduzidas é necessário passar como segundo parâmetro da função __ o text domain / slug do plugin

2024-04-20 18:42 UTC, emanuellopess commented on includes/class-lkn-wc-gateway-cielo-debit.php
> +            $error_message = "Return Code: " . $responseDecoded->Payment->ReturnCode . '. Return Message: ' . $responseDecoded->Payment->ReturnMessage . '.' . __('Please contact Cielo for further ass
@helonfranca02 No caso de tradução de mensagem precisa passar o segundo parâmetro do text domain

2024-04-20 18:44 UTC, emanuellopess requested changes
@helonfranca02 Lembrete, verifique se o código do débito não está rodando para outros métodos de pagamento, no caso débito ativo porém não selecionado, principalmente no caso de carrinho de compras.

O ideal é nem carregar o script 3DS caso o débito esteja desabilitado, talvez só carregar o 3DS quando a opção de pagamento cartão de débito for selecionada.

2024-04-22 18:24 UTC, helonfranca02 commented on includes/class-lkn-wc-gateway-cielo-credit.php
> +                'description' => __('Cielo API- sddasd 3.0 environment.', 'lkn-wc-gateway-cielo'),
Resolvido.

2024-04-22 18:27 UTC, helonfranca02 commented on includes/class-lkn-wc-gateway-cielo-credit.php
> +            $error_message = "Return Code: " . $responseDecoded->Payment->ReturnCode . '. Return Message: ' . $responseDecoded->Payment->ReturnMessage . '.' . __('Please contact Cielo for further ass
Resolvido.

2024-04-22 18:27 UTC, helonfranca02 commented on includes/class-lkn-wc-gateway-cielo-debit.php
> +            $error_message = "Return Code: " . $responseDecoded->Payment->ReturnCode . '. Return Message: ' . $responseDecoded->Payment->ReturnMessage . '.' . __('Please contact Cielo for further ass
Resolvido.

2024-04-22 19:39 UTC, helonfranca02 commented
Concluída a alteração solicitada no pull request. Em relação ao comentário sobre o script do 3DS, foi resolvido na issue https://github.com/LinkNacional/wc_cielo_payment_gateway/issues/34. Agora, ele só carrega o script caso o cartão de débito esteja selecionado; caso contrário, o script não é carregado em nenhuma página. Isso também foi corrigido em outros plugins, como o [woocommerce-invoice-payment](https://github.com/LinkNacional/woocommerce-invoice-payment).

2024-05-02 14:15 UTC, emanuellopess approved these changes

2024-05-02 14:35 UTC, merged