1.10.0 Habilitar recurso de 3DS para crédito e débito
LinkNacional/wc_cielo_payment_gateway pull request #69
Opened 2024-06-27 17:31 UTC by GuilhermeLinkNacional

- Adição de pagamentos de crédito com validação 3DS;
- Adição de validação de BIN para selecionar tipo de cartão automáticamente.

2024-06-28 18:16 UTC, Abraao2005 requested changes

2024-06-28 18:16 UTC, Abraao2005 commented on includes/LknWCGatewayCieloEndpoint.php
> +            'callback' => array($this, 'orderCapture'),
dando erro nessa parte

Precisa dar permissão ao endpoint para ele retornar 

  'permission_callback' => '__return_true',

2024-07-03 19:29 UTC, helonfranca02 approved these changes

2024-07-30 20:22 UTC, emanuellopess approved these changes

2024-07-30 20:22 UTC, merged