1.11.0 Adição compatibilidade com configuração para alterar status quando o pedido for pago
LinkNacional/wc_cielo_payment_gateway pull request #87
Opened 2024-09-02 17:49 UTC by GuilhermeLinkNacional

* Adição de traduções para campo de CPF para pagamentos com Pix.
* Adição compatibilidade com configuração para alterar status quando o pedido for pago.

2024-09-05 22:15 UTC, emanuellopess commented on includes/LknWCGatewayCieloCredit.php
> +            apply_filters("lkn_wc_cielo_change_order_status", $order, $this);
@GuilhermeLinkNacional Muito importante, apply_filters geralmente é aplicado no contexto de modificação de valores e atribuído a uma variável: 

```php
// Retorna variável $order após modificá-la via filtro 
$order = apply_filters('filtro', $order, $this);
```

É possível utilizar mas se o order modificado não será usado posteriormente um [do_action](https://developer.wordpress.org/reference/functions/do_action/) pode fazer mais sentido

2024-09-05 22:15 UTC, emanuellopess requested changes
@GuilhermeLinkNacional Necessita ajustes

2024-09-06 16:22 UTC, Abraao2005 approved these changes

2024-09-14 13:46 UTC, emanuellopess approved these changes

2024-09-14 13:46 UTC, merged